# NAME OF THE IMAGE, LOCALLY OR ONLINE INTO THE DOCKERHUB
FROM node

# THIS WILL BE THE ROOT 
WORKDIR /app

# FILES THAT WILL GO INTO THE IMAGE. WITH THE . WE TELL THE SAME FOLDER THAT CONTAINS THE DOCKERFILE, THE SECOND PARAM IS THE PATH INSIDE OF THE IMAGE WHERE THE FILES SHOULD BE STORED
COPY . /app

# AFTER COPIED, I WANT TO RUN A COMMAND. THE COMMANDS HAVE EFFECT INTO THE ROOT DIRECTORY, IN THIS CASE /app. IF THE ARE THE WORKDIR COMMAND, THE COMMAND RUNS THERE, IF THERE AREN'T, THE COMMAND WILL RUN INTO THE FOLDER SPECIFIED INTO COPY
RUN npm install

# EXPOSE ON THE PORT, SAME IN OUR server.js FILE
EXPOSE 80

# WITH THIS COMMAND WE MAKE SURE TO RUN IT WHEN A CONTAINER IS STARTED AND NOT WHEN AN IMAGE IS CREATED
# CMD node server.js TURNS LIKE
# IT MUST BE THE LAST INSTRUCTION
CMD ["node", "server.js"]